### PR TITLE
Update SEQTA.js

### PR DESCRIPTION
**Pull request by norangeflame**
My modifications if you want them. They fix formatting issues that I had in the Notices on the Home page of BetterSEQTA.

### CODE REVIEW

**Comment by norangeflame** [comment]
I think the code formatting got scuffed sorry.

**Comment by norangeflame** [comment]
If I've done something wrong please tell me, I've literally never made a pull request before.

**Comment by Crazypersonalph** [comment]
So the funny thing is, I just made a new patch (using parts of your code) that removes the need for an extra function, so this is now unnecessary :/

Since you are the author of this code section, I'll still give you credit for the implementation details.

Thanks for your contribution, I'm sorry about that

**Comment by norangeflame** [comment]
That's cool, you've probably done a much better job than me.

**Comment by norangeflame** [comment]
I sort of just did an easy fix instead of going for the root problem.

**Comment by norangeflame** [comment]
I see what you've changed, nice job. That makes it much simpler.

**Pull request closed without merging**
